- name: Prepare nodes
  hosts: k8s_cluster
  become: true
  roles:
    - common

- name: Installer containerd
  hosts: k8s_cluster
  become: true
  roles:
    - containerd

- name: Initialize control plane
  hosts: masters
  become: true
  roles:
    - kubeadm-init

- name: Join workers to cluster
  hosts: workers
  become: true
  roles:
    - kubeadm-join

- name: Install Cilium
  hosts: masters
  become: true
  roles:
    - install-cilium
