# roles/kubeadm-init/tasks/main.yml

- name: Install kubeadm, kubelet, kubectl
  include_tasks: ../common/tasks/kubernetes-tools.yml

- name: Add Kubernetes aliases to user 
  include_tasks: ./add-k8s-aliases.yml

- name: Copy init.sh to remote host
  copy:
    src: init.sh
    dest: /tmp/init.sh
    mode: '0755'

- name: Execute the init.sh script
  shell: /tmp/init.sh
  register: script_output
  ignore_errors: false

- name: Print script stdout
  debug:
    var: script_output.stdout_lines

- name: Print script stderr
  debug:
    var: script_output.stderr_lines

- name: Fail with error if script fails
  fail:
    msg: "Script failed with error: {{ script_output.stderr }}"
  when: script_output.rc != 0

- name: Remove the script after execution
  file:
    path: /tmp/init.sh
    state: absent

# - name: Initialize Kubernetes master
#   shell: |
#     kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }} --ignore-preflight-errors=all
#   args:
#     creates: /etc/kubernetes/admin.conf

- name: Ensure $HOME/.kube exist
  file:
    path: $HOME/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig to $HOME/.kube/config
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: true

- name: Generate kubeadm join script
  shell: |
    kubeadm token create --print-join-command --ttl 24h > /tmp/kubeadm_join.sh
    chmod +x /tmp/kubeadm_join.sh
  args:
    creates: /tmp/kubeadm_join.sh

- name: Read kubeadm join script content into variable
  slurp:
    src: /tmp/kubeadm_join.sh
  register: join_script