# roles/common/tasks/main.yml
- name: Install required packages
  apt:
    name:
      - curl
      - tree
      - net-tools
      - git
      - rsyslog
      - dnsutils
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - gpg
      - gnupg
      - software-properties-common
      - htop
      - sudo
    update_cache: true


