# roles/kubeadm-join/tasks/main.yml

- name: Install kubeadm, kubelet, kubectl
  include_tasks: ../common/tasks/kubernetes-tools.yml

- name: Copy kubeadm join script to worker
  copy:
    content: "{{ hostvars['master']['join_script']['content'] | b64decode }}"
    dest: /tmp/kubeadm_join.sh
    mode: '0700'

- name: Execute kubeadm join
  shell: bash /tmp/kubeadm_join.sh
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: Copy join command script from master
  fetch:
    src: /tmp/kubeadm_join.sh
    dest: /tmp/kubeadm_join.sh
    flat: yes
  delegate_to: master
  run_once: true

- name: Run join script
  shell: bash /tmp/kubeadm_join.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
